export const cuisineList = [
  'Butter Chicken',
  'Biryani',
  'Masala Dosa',
  'Paneer Tikka',
  'Rogan Josh',
  'Chole Bhature',
  'Vada Pav',
  'Pani Puri',
  'Tandoori Chicken',
  'Aloo Paratha',
  'Hyderabadi Biryani',
  'Pav Bhaji',
  'Dhokla',
  'Rasgulla',
  'Kebabs',
  'Gulab Jamun',
  'Idli',
  'Samosa',
  'Macher Jhol',
  'Poha',
  'Bhutte ka Kees',
  'Dal Bafla',
  'Goan Fish Curry',
  'Baati Chokha',
  'Kadhi',
];
